### PR TITLE
Change SafeBluetooth's handler to run on the main thread

### PR DESCRIPTION
**Pull request by paulmandal**
When calling `MeshService.setDeviceAddress(String)` from my application I'd get an exception in the `MeshService` like this:

```
23130-23147/com.geeksville.mesh E/toRemoteExceptions: Uncaught exception, returning to remote client
    java.lang.RuntimeException: Can't create handler inside thread Thread[Binder:23130_1,5,main] that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:207)
        at android.os.Handler.<init>(Handler.java:119)
        at com.geeksville.mesh.service.SafeBluetooth.<init>(SafeBluetooth.kt:100)
        at com.geeksville.mesh.service.BluetoothInterface.<init>(BluetoothInterface.kt:210)
        at com.geeksville.mesh.service.RadioInterfaceService.startInterface(RadioInterfaceService.kt:234)
        at com.geeksville.mesh.service.RadioInterfaceService.setBondedDeviceAddress(RadioInterfaceService.kt:304)
        at com.geeksville.mesh.service.RadioInterfaceService.access$setBondedDeviceAddress(RadioInterfaceService.kt:37)
        at com.geeksville.mesh.service.RadioInterfaceService$binder$1$setDeviceAddress$1.invoke(RadioInterfaceService.kt:312)
        at com.geeksville.mesh.service.RadioInterfaceService$binder$1$setDeviceAddress$1.invoke(RadioInterfaceService.kt:309)
        at com.geeksville.util.ExceptionsKt.toRemoteExceptions(Exceptions.kt:56)
        at com.geeksville.mesh.service.RadioInterfaceService$binder$1.setDeviceAddress(RadioInterfaceService.kt:311)
        at com.geeksville.mesh.service.MeshService$binder$1$setDeviceAddress$1.invoke(MeshService.kt:1538)
        at com.geeksville.mesh.service.MeshService$binder$1$setDeviceAddress$1.invoke(MeshService.kt:1533)
        at com.geeksville.util.ExceptionsKt.toRemoteExceptions(Exceptions.kt:56)
        at com.geeksville.mesh.service.MeshService$binder$1.setDeviceAddress(MeshService.kt:1535)
        at com.geeksville.mesh.IMeshService$Stub.onTransact(IMeshService.java:274)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

This patch modifies `SafeBluetooth`'s `Handler` to run on the main thread which allows 3rd party integrations to call `MeshService.setDeviceAddress(String)` successfully.

### CODE REVIEW

**Comment by geeksville** [comment]
Super cool!  Btw - how are you handling access to the various Parcelables we expose?  I realized later that I should have probably put all that stuff (along with the aidl file) into a separate library so that clients could link that into their code.

**Comment by paulmandal** [comment]
@geeksville Thanks man! For the time being I just copied `LocationUtils.kt`, `DataPacket.kt`, `MyNodeInfo.kt`, `NodeInfo.kt`, and `anonymize.kt` into my project so I can work with those Parcelables. And I added the Meshtastic protobufs as a submodule so I can use `setRadioConfig()`.

**Comment by geeksville** [comment]
ok - I'll try to refactor those into a lib (now that I know someone other
than me has a use for them ;-).  Hopefully later this week.

**Comment by paulmandal** [comment]
Awesome man, thank you! I really appreciate all the work on this project -- it's been great using it!

**Comment by geeksville** [comment]
ok WIP here: https://github.com/geeksville/Meshtastic-Android/tree/splitlib/mesh_shared

I'll finish sometime this week (not ready for use yet) and put up on jitpack or something.

**Pull request merged**
