### PR TITLE
Show app version in the app #5

### PR DESCRIPTION
**Pull request by lgoix**
about

### CODE REVIEW

**Comment by lgoix** [comment]
Please test with a newer Android version, I am on Android 6.0

**Comment by geeksville** [comment]
ooh cool! thanks.  I'll download and test it tomorrow (I'll also be doing a bit of autobug triage/fixing)

**Comment by lgoix** [comment]
It displays a toast for the moment, the works was focused on the overflow menu, i will add a debug menu item to display the log, like every communication from the radio

**Comment by geeksville** [comment]
that sounds great!

**Pull request merged**
