### PR TITLE
feat: add text/plain intent to send message 

### PR DESCRIPTION
**Pull request by remi-espie**
This PR adds a text/plain intent that allow user to share a piece of text to a Meshtastic node through the application.

This PR is currently a WIP. As of right now, only the intent was added. 

The PR idea would be 2 fold:
1. Add a way to easily share the text to a user-selected contact. For this, I thought of adding an optional `txtToFill` variable to the [`navigateToMessages`](https://github.com/meshtastic/Meshtastic-Android/blob/227c65f1914cd5b4b379e94070bafc0463b08eb5/app/src/main/java/com/geeksville/mesh/ui/MessagesFragment.kt#L40) function (or create a new function altogether). If not empty, this variable would autofill the text input of the selected contact.
2. Create some kind of JSON struct that would be auto parsed, like 
```json
{
"contactKey": string,
"contactName": string,
"message": string,
"autosSend": bool
}
```

Upon completion, this PR would solve #1062 .

### CODE REVIEW

**Comment by jamesarich** [comment]
I have been thinking about this in conjunction with direct reply from the notification - I'm hoping that these would use similar methods/intents to collect and deliver to the appropriate places.

**Comment by remi-espie** [comment]
I decided to scale down this PR to solely be able to share a string of text, removing the json parser auto sending messages.
I had trouble with the auto sending of messages. It may be a part of a future PR.

This PR adds:
- the ability to share text content to a contact
- a new screen to share to
- solve #1062

**Comment by Neo-Oli** [comment]
@remi-espie Do you still intend to create this auto send feature? I would very much like a way to fully automate the sending of messages from another app.

**Comment by remi-espie** [comment]
Hello,
While working on that, I saw that Meshtastic has a broadcast service. I didn't find in the the documentation, but the code is pretty straightforward (see [MeshServiceBroadcast](app/src/main/java/com/geeksville/mesh/service/MeshServiceBroadcasts.kt)). 
I don't plan to work on this feature right now, but I think it would be better to expand the broadcast service instead of an intent to send message automatically (as it would make sending messages programmatically easier).

**Pull request merged**
