### PR TITLE
Feature: Camera QR Code scanning

### PR DESCRIPTION
**Pull request by andrekir**
Basic QR Code scanning feature using ZXing library IntentIntegrator.

Requires:
- android.permission.CAMERA

### CODE REVIEW

**Comment by geeksville** [comment]
ooh sounds promising.

**Comment by andrekir** [comment]
not sure how to deal with the camera permission. treating CAMERA as minimal requirement (current logic) seems excessive (persistent warnings, no camera = quit).

can we just let Android deal with the Camera permission? or could this break early Android versions 6.0+?)

feedback appreciated!

**Comment by andrekir** [comment]
Added camera permissions following best practices: https://developer.android.com/guide/topics/permissions/overview

- Ask for permissions in context, when the user starts to interact with the feature that requires it.
- Don't block the user. Always provide the option to cancel an educational UI flow related to permissions.
- If the user denies or revokes a permission that a feature needs, gracefully degrade your app so that the user can continue using your app, possibly by disabling the feature that requires the permission.
- Don't assume any system behavior. For example, don't assume that permissions appear in the same permission group. A permission group merely helps the system minimize the number of system dialogs that are presented to the user when an app requests closely-related permissions.

**Comment by mc-hamster** [comment]
Merged. Error is with map box.

**Comment by geeksville** [comment]
This pull request has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-android-1-2-51-alpha/4503/1

**Pull request merged**
