### PR TITLE
feat: add detekt Android CI workflow, migrate to ktlint plugin

### PR DESCRIPTION
**Pull request by jamesarich**
This adds the ci workflow job for detekt.
image

migrates ktlint functionality to detekt plugin

From there, @andrekir, you should be able to add the required check to the branch protection settings, if desired.

### CODE REVIEW

**Comment by jamesarich** [comment]
sorry for the churn - first time using github ci

**Comment by andrekir** [comment]
can we have all ktlint/detekt files in their respective `/config` folders?

https://github.com/meshtastic/Meshtastic-Android/blob/72d78372d89169daf9790165a2bbf2de873efdbc/config/ktlint/baseline.xml#L1-L2

https://github.com/meshtastic/Meshtastic-Android/blob/72d78372d89169daf9790165a2bbf2de873efdbc/app/config/ktlint/baseline.xml#L1-L2

https://github.com/meshtastic/Meshtastic-Android/blob/72d78372d89169daf9790165a2bbf2de873efdbc/config/detekt/detekt.yml#L1-L2

https://github.com/meshtastic/Meshtastic-Android/blob/72d78372d89169daf9790165a2bbf2de873efdbc/app/detekt-baseline.xml#L1-L2

**Comment by jamesarich** [comment]
Put the configs and baselines in the respective root /config folders and updated gradle configs to look for them there.

**Comment by jamesarich** [comment]
actually - doing some reading and i may scrap ktlint entirely in favor of just using the ktlint formatting rules plugin available to detekt - moving this back to draft.

**Comment by jamesarich** [comment]
Ok, just using the ktlint detekt plugin now.

**Pull request merged**
