### PR TITLE
MeshService cleanup

### PR DESCRIPTION
**Pull request by KenVanHoeylandt**
# Changes
- created `MeshServiceAnalytics`
- created `MeshServiceNodeDatabase`
- created `IRadioInterfaceServiceExt` with extension functions
- `MeshPacket` file with extension functions
- `Time.kt with` time helpers
- Misc. cleanup

# Testing

I used a debug build as follows:

## Devices

- 2x TTGO Lora32 v2.1 (it says "T3 v1.6" on the back)
- 1x Nexus 5x
- 1x Motoral G9 Play (App works, but BT fails. Issue already existed at commit `f9e39b66a4f0a25286a0dbe0e6486ce472940f8e`)

# Actions

- connecting and disconnecting phone from both TTGO devices in app
- switching tabs
- sending messages (send verification on phone, receive verification on TTGO devices only)

### CODE REVIEW

**Comment by lgoix** [comment]
I've been able to fix the CI to perform merge. All unit test must pass before merging, that is a good news

**Comment by geeksville** [comment]
@lgoix Thanks for fixing CI!
@KenVanHoeylandt from the log above I think the failing test is here:

e: /home/runner/work/Meshtastic-Android/Meshtastic-Android/app/src/test/java/com/geeksville/mesh/service/MeshServiceTest.kt: (18, 9): Unresolved reference: updateNodeInfoTime

(you can also run this locally in gradlew)

**Comment by geeksville** [comment]
@KenVanHoeylandt do you want to try fixing that unit test or do you want me to have a go at it? (sorry - I've been away a few days)

**Comment by KenVanHoeylandt** [comment]
@geeksville Sorry, I've been busy with other things, but I'll take a look at it!

**Comment by geeksville** [comment]
HI @KenVanHoeylandt just checking in: do you think you'll still be able to do this cleanup?

**Comment by geeksville** [comment]
ok @KenVanHoeylandt closing for now, welcome whenver you want to return

**Pull request closed without merging**
