### PR TITLE
feat: Add notification for new node seen

### LINKED ISSUE #914: Android notification on new node i db
Feature request

Option to have the app make a notification in Android notification when new node is found in the mesh and added to the database. 
Should maybe be disabled as default

### PR DESCRIPTION
**Pull request by jamesarich**
Proposed change:  I'd like to know when a new node is seen/added to the NodeDb

Adds new Android notification when new node is seen.

resolves #914

### CODE REVIEW

**Comment by jamesarich** [comment]
I've got the basic legwork done for displaying a new notification. @andrekir Where do you think is a good place to hook into `MeshService` for determining if a new node is seen?

Is 3 notifications ( `status`, `message`, and now `new node` ) too many notifications?

**Comment by andrekir** [comment]
> Where do you think is a good place to hook into `MeshService` for determining if a new node is seen?

I think [`handleReceivedUser()`](https://github.com/meshtastic/Meshtastic-Android/blob/2050cd0b4b14ac585e5358c6b67117d59b3d3e66/app/src/main/java/com/geeksville/mesh/service/MeshService.kt#L801) is a  good spot to tap into.

I also added a new [`NodeEntity.isUnknownUser`](https://github.com/meshtastic/Meshtastic-Android/blob/master/app/src/main/java/com/geeksville/mesh/database/entity/NodeEntity.kt#L87) property to help flag unknown nodes that you can use.

> Is 3 notifications ( `status`, `message`, and now `new node` ) too many notifications?

separate notification channels for new nodes is better. that way, users can control what type of notifications they receive.

**Comment by jamesarich** [comment]
Ok @andrekir - should be ready for review. I left things fairly simple.
Screenshot_20241014_175517
Screenshot_20241014_175834

**Comment by deonte1threatt** [comment]
While I loved this addition, is it possible to have it on a different notification channel?  It helps with selecting how that notification is delivered

**Comment by jamesarich** [comment]
> While I loved this addition, is it possible to have it on a different notification channel? It helps with selecting how that notification is delivered

Unless I'm misunderstanding your question - this is already the case, an individual channel is being created for these notifications. [See here for implementation details](https://github.com/meshtastic/Meshtastic-Android/blob/700d8d3460eff858c216c4eef5e9d254fcfd5811/app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt#L130).

sEoTiGp (1)

**Comment by Firecul** [comment]
> @deonte1threatt Unless I'm misunderstanding your question - this is already the case, an individual channel is being created for these notifications. [See here for implementation details](https://github.com/meshtastic/Meshtastic-Android/blob/700d8d3460eff858c216c4eef5e9d254fcfd5811/app/src/main/java/com/geeksville/mesh/service/MeshServiceNotifications.kt#L130).

I get where @deonte1threatt was coming from it didn't look separated as you had mentioned earlier to myself either but your screenshot shows it is 👍

**Comment by deonte1threatt** [comment]
Ignore me.  Samsung disabled that by default.

**Pull request merged**
