### PR TITLE
improve documentation for usage of bound service

### PR DESCRIPTION
**Pull request by mertrois**
## Thank you for sending in a pull request, here's some tips to get started!

re-submitting PR after sorting out username issues.

### CODE REVIEW

**Comment by andrekir** [comment]
thanks for sharing your findings. interesting, just confirmed this isn't always necessary. can you change the wording (adding may or could need) to reflect this?

**Comment by mertrois** [comment]
https://stackoverflow.com/questions/67114596/unable-to-bind-to-service-after-moving-to-android-11

Interesting, yeah I struggled with this for 2 days before adding this and successfully connecting. Trying to save someone else days of wasted time.

**Review by mertrois — COMMENTED** [review]
as requested.

**Comment by andrekir** [comment]
thank you.

**Pull request merged**
