### PR TITLE
Qr channel select

### PR DESCRIPTION
**Pull request by Robert-0410**
#### Addressing Issue #635
These changes allow the user to select what channels they want included in the URL/QR.

### CODE REVIEW

**Comment by Robert-0410** [comment]
> Does this PR do anything for #953 or is it only for selecting which channels to share?
I'm not aware of what "add=true" is. Is it something meant to help with the feature?

**Comment by Robert-0410** [comment]
> > > Does this PR do anything for #953 or is it only for selecting which channels to share?
> > 
> > 
> > I'm not aware of what "add=true" is. Is it something meant to help with the feature?
> 
> It would be so when you add selected channels from a QR code, they’ll be added versus overwriting all channels. It was recently added in the Apple apps: [meshtastic/Meshtastic-Apple@2a38dbb](https://github.com/meshtastic/Meshtastic-Apple/commit/2a38dbbb1cfab3b25e9bd1ae9b6b62c10ed5d0bd)

Understood, These commits don't provide said feature.
But I wouldn't mind working on it after this.

**Review by andrekir — CHANGES_REQUESTED** [review]
while the effort is appreciated, this implementation is needlessly complex. the changes to `Channel`, `ChannelSet`, and viewmodel are unnecessary. instead, simply filter the checked channels to build a `ChannelSet` and generate the QR code/URL from that.

also consider using a separate UI screen or modal for channel selection and QR code/URL generation, for example, similar to how it’s done in the web app:

ezgif-1-bcf3779d20

**Comment by Robert-0410** [comment]
Thanks for the feedback at @andrekir , and I appreciate the hard work that has gone into the app.

Ill take another crack at it 🏗️

**Comment by Robert-0410** [comment]
Took a fresh approach with #1051

**Pull request closed without merging**
