### PR TITLE
Feature: Filter node list

### PR DESCRIPTION
**Pull request by daviscodesbugs**
Adds a text field to the node list that filters against node short name and long name. Filter updates with each character

Fulfills #683

### CODE REVIEW

**Comment by prokrypt** [comment]
would it be easy to have it search nodeid too, for times when we need to look up a mystery node?

**Comment by andrekir** [comment]
looks good!

since the filter can remove `node[0]`, one small change is needed at: https://github.com/meshtastic/Meshtastic-Android/blob/44aa28554bce0796574c7af94944752b0ead00a5/app/src/main/java/com/geeksville/mesh/ui/UsersFragment.kt#L182-L183

 we can use `model.ourNodeInfo.value` here and update `thisNodeInfo` param type to `NodeInfo?`.

**Comment by davis-gotenna** [comment]
@andrekir 
Finally getting back to this; should be good now!

**Comment by daviscodesbugs** [comment]
@andrekir
Finally getting back to this; should be good now!

**Comment by andrekir** [comment]
looks great, thanks!

**Pull request merged**
