### PR TITLE
Refactored MeshService

### PR DESCRIPTION
**Pull request by KenVanHoeylandt**
# Changes

- moved `MeshService` start-related code to `MeshServiceStarter`
- moved `LocationCallback` to `MeshServiceLocationCallback`
  - coroutine scope is now handled in `MeshService` position callback
  - refactored `onLocationResult()` to be easier to read
- created `MeshServiceNotifications` for creating and updating of notifications
- moved `SavedSettings` to `MeshServiceSettingsData`
- some renames for consistency, like `MeshService.startService()` versus `MeshService.startServiceLater()`
- misc. cleanup of `MeshService`

# Notable

When `MeshServiceLocationCallback.onLocationResult()` is called, the code is now not _entirely_ ran on the coroutine scope anymore. Only the actual sending of the message is now done in this scope. This call still happens inside of `MeshService` and not in the location callback itself.

# Testing

I used a debug build as follows:

## Devices
- 2x TTGO Lora32 v2.1 (it says "T3 v1.6" on the back)
- 1x Nexus 5x

## Actions
- connecting and disconnecting phone from both TTGO devices in app
- switching tabs
- sending messages (send verification on phone, receive verification on TTGO devices only)
- pending notifications (clicked it)

### CODE REVIEW

**Comment by lgoix** [comment]
I don't understand the problem 
image

**Comment by geeksville** [comment]
@lgoix yeah - there is something sick in the android build CI script, I'll need to look at it.

@KenVanHoeylandt thanks!  I'll read and reply later today, sounds great - catching up on github now in Taiwan.

**Comment by geeksville** [comment]
looks great to me.  I'll push out an alpha with this tomorrow!

**Comment by KenVanHoeylandt** [comment]
Good to hear! Consider that I have more refactoring changes pending for this service. I have a separate branch that is based on this branch, but I haven't pushed it yet.

**Pull request merged**
